base:
  # Path to the folder containing the data. One of [data, data_aio, data_aio_x]
  folder: data_aio_x

  # Output directory for the experiment results
  output: output

  # Random seed for reproducibility
  seed: 42

  # Hugging Face repository for the model
  hf_repo: CompVis/stable-diffusion-v1-4

  # Number of diffusion timesteps
  timesteps: 30

  # Percentage of diffusion steps to use
  diffusion_percent: 1/3

  # Device to run the experiments on
  device: cuda


  # Type of classifier to use. One of [lstm, gru, transformer]
  classifier_type: lstm

  # Hyperparameters for the classifier
  hidden_size: 64
  num_layers: 1
  num_classes: 2

  # Training hyperparameters
  batch_size: 8
  epochs: 50
  lr: 1.e-3
  weight_decay: 1.e-5


  # Name of the experiment
  experiment_name: default_experiment

  # Included features to be extracted in the experiments. Any of [noise_stats, noise_fft, residual_stats, cos_sim]
  included_features:
    - noise_stats
    - noise_fft
    - residual_stats
    - cos_sim

# List of experiments to run
# Each experiment can override the base configuration
experiments: