base:
  # Name of the experiment
  experiment_name: default_experiment

  # Path to the folder containing the data. One of [data, data_aio, data_aio_x]
  data_dir: data_aio_x

  # Output directory for the experiment results
  output_dir: output

  # Random seed for reproducibility
  seed: 42

  # Hugging Face repository for the model
  hf_repo: CompVis/stable-diffusion-v1-4

  # Number of diffusion timesteps
  timesteps: 30

  # Number of diffusion steps to use
  diffusion_steps: 10

  # Device to run the experiments on
  device: cuda


  # Type of classifier to use. One of [lstm, gru, transformer]
  classifier_type: lstm

  # Hyperparameters for the classifier
  hidden_size: 64
  num_layers: 1
  num_classes: 2

  # Training hyperparameters
  batch_size: 8
  epochs: 50
  lr: 1.e-3
  weight_decay: 1.e-5

  # Included features to be extracted in the experiments. Any of [noise_stats, noise_fft, residual_stats, cos_sim]
  included_features:
    - noise_stats
    - noise_fft
    - residual_stats
    - cos_sim

# List of runs to execute
# Each run can override the base configuration
runs:

    # Name of the run
  - run_name: default_run