base:
  folder: data_x
  output: generalisation_exp
  seed: 42
  hf_repo: CompVis/stable-diffusion-v1-4
  timesteps: 30
  diffusion_percent: 1/3
  device: cuda

  classifier_type: lstm
  hidden_size: 64
  num_layers: 1
  num_classes: 2

  batch_size: 8
  epochs: 50
  lr: 1.e-3
  weight_decay: 1.e-5

  experiment_name: noise_stats noise_fft residual_stats cos_sim
  included_features:
    - noise_stats
    - noise_fft
    - residual_stats
    - cos_sim

experiments:
