base:
  folder: data_aio_x
  output: features_40_1_2_exp
  seed: 42
  hf_repo: CompVis/stable-diffusion-v1-4
  timesteps: 40
  diffusion_percent: 0.5
  device: cuda

  classifier_type: lstm
  hidden_size: 64
  num_layers: 1
  num_classes: 2

  batch_size: 8
  epochs: 50
  lr: 1.e-3
  weight_decay: 1.e-5

experiments:
  - experiment_name: noise_stats
    included_features:
      - noise_stats

  - experiment_name: noise_fft
    included_features:
      - noise_fft

  - experiment_name: residual_stats
    included_features:
      - residual_stats

  - experiment_name: cos_sim
    included_features:
      - cos_sim

  - experiment_name: noise_stats noise_fft
    included_features:
      - noise_stats
      - noise_fft

  - experiment_name: noise_stats residual_stats
    included_features:
      - noise_stats
      - residual_stats

  - experiment_name: noise_stats cos_sim
    included_features:
      - noise_stats
      - cos_sim

  - experiment_name: noise_fft residual_stats
    included_features:
      - noise_fft
      - residual_stats

  - experiment_name: noise_fft cos_sim
    included_features:
      - noise_fft
      - cos_sim

  - experiment_name: residual_stats cos_sim
    included_features:
      - residual_stats
      - cos_sim

  - experiment_name: noise_stats noise_fft residual_stats
    included_features:
      - noise_stats
      - noise_fft
      - residual_stats

  - experiment_name: noise_stats noise_fft cos_sim
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim

  - experiment_name: noise_stats residual_stats cos_sim
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - experiment_name: noise_fft residual_stats cos_sim
    included_features:
      - noise_fft
      - residual_stats
      - cos_sim

  - experiment_name: noise_stats noise_fft residual_stats cos_sim
    included_features:
      - noise_stats
      - noise_fft
      - residual_stats
      - cos_sim