experiment_name: features_20_30_exp
type: generic
data_dir: data_aio
output_dir: features_20_30_exp
x_train_samples: -1
x_test_samples: -1

base:
  seed: 42

  hf_repo: CompVis/stable-diffusion-v1-4
  timesteps: 30
  diffusion_steps: 20
  device: cuda

  classifier_type: lstm
  hidden_size: 64
  num_layers: 3
  num_classes: 2

  batch_size: 8
  epochs: 50
  lr: 1.e-3
  weight_decay: 1.e-5

runs:
  - run_name: ns
    included_features:
      - noise_stats

  - run_name: nfft
    included_features:
      - noise_fft

  - run_name: rs
    included_features:
      - residual_stats

  - run_name: cs
    included_features:
      - cos_sim

  - run_name: ns_nfft
    included_features:
      - noise_stats
      - noise_fft

  - run_name: ns_rs
    included_features:
      - noise_stats
      - residual_stats

  - run_name: ns_cs
    included_features:
      - noise_stats
      - cos_sim

  - run_name: nfft_rs
    included_features:
      - noise_fft
      - residual_stats

  - run_name: nfft_cs
    included_features:
      - noise_fft
      - cos_sim

  - run_name: rs_cs
    included_features:
      - residual_stats
      - cos_sim

  - run_name: ns_nfft_rs
    included_features:
      - noise_stats
      - noise_fft
      - residual_stats

  - run_name: ns_nfft_cs
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim

  - run_name: ns_rs_cs
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: nfft_rs_cs
    included_features:
      - noise_fft
      - residual_stats
      - cos_sim

  - run_name: ns_nfft_rs_cs
    included_features:
      - noise_stats
      - noise_fft
      - residual_stats
      - cos_sim