experiment_name: full_dataset_exp
type: generic
data_dir: data_aio
output_dir: full_dataset_exp
x_train_samples: -1
x_test_samples: -1

base:
  seed: 42

  hf_repo: CompVis/stable-diffusion-v1-4
  timesteps: 30
  diffusion_steps: 20
  device: cuda

  classifier_type: lstm
  hidden_size: 64
  num_layers: 3
  num_classes: 2

  batch_size: 8
  epochs: 200
  lr: 1.e-5
  weight_decay: 1.e-7

runs:

  - run_name: lstm_ns_nfft
    classifier_type: lstm
    included_features:
      - noise_stats
      - noise_fft

  - run_name: lstm_ns_rs_cs
    classifier_type: lstm
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: lstm_ns_nfft_cs
    classifier_type: lstm
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim

  - run_name: gru_ns_nfft
    classifier_type: gru
    included_features:
      - noise_stats
      - noise_fft

  - run_name: gru_ns_rs_cs
    classifier_type: gru
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: gru_ns_nfft_cs
    classifier_type: gru
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim

  - run_name: transformer_ns_nfft
    classifier_type: transformer
    included_features:
      - noise_stats
      - noise_fft

  - run_name: transformer_ns_rs_cs
    classifier_type: transformer
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: transformer_ns_nfft_cs
    classifier_type: lstm
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim

  - run_name: first_ns_nfft
    classifier_type: first
    included_features:
      - noise_stats
      - noise_fft

  - run_name: first_ns_rs_cs
    classifier_type: first
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: first_ns_nfft_cs
    classifier_type: first
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim

  - run_name: last_ns_nfft
    classifier_type: last
    included_features:
      - noise_stats
      - noise_fft

  - run_name: last_ns_rs_cs
    classifier_type: last
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: last_ns_nfft_cs
    classifier_type: last
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim
