base:
  experiment_name: full_dataset_exp
  data_dir: data_aio
  output_dir: full_dataset_exp
  seed: 42
  hf_repo: CompVis/stable-diffusion-v1-4
  timesteps: 30
  diffusion_steps: 20
  device: cuda

  classifier_type: lstm
  hidden_size: 64
  num_layers: 3
  num_classes: 2

  batch_size: 8
  epochs: 50
  lr: 1.e-3
  weight_decay: 1.e-5

runs:

  - run_name: ns_nfft
    included_features:
      - noise_stats
      - noise_fft

  - run_name: ns_rs_cs
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: ns_nfft_cs
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim
