experiment_name: full_dataset_exp
type: generic
data_dir: data_aio
output_dir: full_dataset_exp
x_train_samples: 400
x_test_samples: 100

base:
  seed: 42

  hf_repo: CompVis/stable-diffusion-v1-4
  timesteps: 30
  diffusion_steps: 20
  device: cuda

  classifier_type: lstm
  hidden_size: 64
  num_layers: 3
  num_classes: 2

  batch_size: 8
  epochs: 50
  lr: 1.e-3
  weight_decay: 1.e-5

runs:

  - run_name: ns_nfft_3l_200e
    num_layers: 3
    epochs: 200
    included_features:
      - noise_stats
      - noise_fft

  - run_name: ns_rs_cs_3l_200e
    num_layers: 3
    epochs: 200
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: ns_nfft_cs_3l_200e
    num_layers: 3
    epochs: 200
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim

  - run_name: ns_nfft_1l_50e
    num_layers: 1
    epochs: 50
    included_features:
      - noise_stats
      - noise_fft

  - run_name: ns_rs_cs_1l_50e
    num_layers: 1
    epochs: 50
    included_features:
      - noise_stats
      - residual_stats
      - cos_sim

  - run_name: ns_nfft_cs_1l_50e
    num_layers: 1
    epochs: 50
    included_features:
      - noise_stats
      - noise_fft
      - cos_sim
